using CWM.RoslynNavigator.Analyzers;
using Microsoft.CodeAnalysis.CSharp;

namespace CWM.RoslynNavigator.Tests.Analyzers;

public class SourceClassifierTests
{
    private static SourceKind Classify(string relativePath, bool isTestProject = false, string source = "class C { }")
    {
        var tree = CSharpSyntaxTree.ParseText(source, path: relativePath);
        return SourceClassifier.Classify(tree, relativePath, isTestProject, TestContext.Current.CancellationToken);
    }

    [Theory]
    [InlineData("src/Api/obj/Debug/net10.0/Api.GlobalUsings.g.cs")]
    [InlineData("src/Api/bin/Release/net10.0/Thing.cs")]
    [InlineData("src/Api/Models.Designer.cs")]
    [InlineData("src/Api/Contracts.generated.cs")]
    [InlineData("src/Api/obj/Api.AssemblyInfo.cs")]
    public void GeneratedPaths_AreGenerated(string path) =>
        Assert.Equal(SourceKind.Generated, Classify(path));

    [Fact]
    public void AutoGeneratedHeader_IsGenerated()
    {
        var source = "// <auto-generated/>\nclass C { }";
        Assert.Equal(SourceKind.Generated, Classify("src/Api/Handwritten.cs", source: source));
    }

    [Theory]
    [InlineData("src/Api/Migrations/20240101_Init.cs")]
    [InlineData("src/Api/Data/AppDbContextModelSnapshot.cs")]
    public void MigrationPaths_AreMigrations(string path) =>
        Assert.Equal(SourceKind.Migration, Classify(path));

    [Theory]
    [InlineData("tests/Api.Tests/OrderTests.cs")]
    [InlineData("src/Api/OrderServiceTests.cs")]
    [InlineData("src/Api/OrderSpec.cs")]
    [InlineData("src/Api/IntegrationTestBase.cs")]
    public void TestPaths_AreTests(string path) =>
        Assert.Equal(SourceKind.Test, Classify(path));

    [Fact]
    public void TestProject_MakesAllItsFilesTests() =>
        Assert.Equal(SourceKind.Test, Classify("src/Api/Helpers.cs", isTestProject: true));

    [Theory]
    [InlineData("src/Api/OrderService.cs")]
    [InlineData("src/Api/Features/Orders/CreateOrder.cs")]
    public void OrdinaryPaths_AreProduction(string path) =>
        Assert.Equal(SourceKind.Production, Classify(path));

    [Theory]
    [InlineData("src/Api/Contest.cs")]
    [InlineData("src/Api/Manifest.cs")]
    [InlineData("src/Api/LatestOrder.cs")]
    public void ProductionNamesEndingInTest_AreNotMisclassified(string path) =>
        Assert.Equal(SourceKind.Production, Classify(path));

    [Fact]
    public void ObjectsFolder_IsNotConfusedWithObjFolder() =>
        Assert.Equal(SourceKind.Production, Classify("src/Api/Objects/Order.cs"));

    [Fact]
    public void GeneratedWins_OverTestProject() =>
        Assert.Equal(
            SourceKind.Generated,
            Classify("tests/Api.Tests/obj/Debug/Api.g.cs", isTestProject: true));
}
