// <auto-generated/>
using SampleDomain;

namespace SampleApi;

/// <summary>
/// Stands in for source-generator output. Both signals SourceClassifier keys on are
/// present: the .g.cs suffix and the auto-generated header comment.
/// </summary>
public sealed class GeneratedOrderSummary
{
    public static string Describe(Order order) => $"{order.Id}:{order.Status}";
}
