#!/usr/bin/env bash
# Pre-commit hook: detect anti-patterns in the lines a commit adds.
#
# This is the no-build tier of the kit's three-tier detection model (ADR-006).
# A git hook runs outside Claude Code, so the Roslyn MCP server is unreachable
# and a full compile is too slow to sit in front of every commit. So this scans
# text — but it scans it carefully: comments and string literals are stripped,
# only added lines are tested, and rules that need a semantic model to be
# certain stay silent rather than guess. Rule IDs, severities, and source-kind
# exemptions match the Roslyn detectors exactly.
#
# For exhaustive, semantically precise analysis, use the Roslyn MCP
# detect_antipatterns tool, or /verify, which runs it.
#
# Suppress a line with a trailing "// cwm:ignore" or "// cwm:ignore AP004".
# Set CWM_ANTIPATTERN_WARN_ONLY=1 to report findings without blocking.
#
# Exit codes:
#   0 — No issues found (or findings downgraded by CWM_ANTIPATTERN_WARN_ONLY)
#   1 — Issues found, commit blocked
#   2 — The hook itself could not run

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCANNER="$SCRIPT_DIR/lib/antipattern-scan.awk"

if [[ ! -f "$SCANNER" ]]; then
    echo "pre-commit-antipattern: scanner not found at $SCANNER" >&2
    exit 2
fi

# Classification uses repo-root-relative paths (an absolute path can contain a
# "tests" or "obj" segment anywhere above the root and misclassify everything
# below it), so run from the root regardless of where git invoked the hook.
REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

# Read one path per line so paths containing spaces stay intact (a plain
# "for FILE in $STAGED_FILES" word-splits them). Uses a while-read loop rather
# than mapfile for bash 3.2 (macOS) compatibility.
STAGED_FILES=()
while IFS= read -r FILE; do
    [[ -n "$FILE" ]] && STAGED_FILES+=("$FILE")
done < <(git diff --cached --name-only --diff-filter=ACM | grep '\.cs$' || true)

if [[ ${#STAGED_FILES[@]} -eq 0 ]]; then
    exit 0
fi

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

# Mirrors SourceClassifier.Classify: generated wins over migration, which wins
# over test. Echoes one of generated|migration|test|production.
classify() {
    local path="$1"
    local name="${path##*/}"
    local stem="${name%.cs}"

    case "/$path" in
        */obj/*|*/bin/*) echo generated; return ;;
    esac
    case "$name" in
        *.g.cs|*.g.i.cs|*.Designer.cs|*.generated.cs|*.AssemblyInfo.cs)
            echo generated; return ;;
    esac
    if git show ":$path" 2>/dev/null | head -5 | grep -qi '<auto-generated'; then
        echo generated; return
    fi

    case "/$path" in
        */Migrations/*) echo migration; return ;;
    esac
    case "$stem" in
        *ModelSnapshot) echo migration; return ;;
    esac

    case "/$path" in
        */tests/*|*/test/*|*/Tests/*|*/Test/*) echo test; return ;;
    esac
    # Case-sensitive so production names like "Contest.cs" or "Manifest.cs" are
    # not mistaken for test files.
    case "$stem" in
        *Tests|*Test|*Spec|*Specs|*TestFixture|*TestBase) echo test; return ;;
    esac

    echo production
}

# Line numbers this commit adds, derived from the staged diff. A pre-existing
# violation on a line the commit does not touch is not this commit's problem —
# without this, one legacy DateTime.Now blocks every future edit to the file.
added_lines() {
    git diff --cached -U0 -- "$1" | awk '
        /^\+\+\+/ { next }
        /^@@/ {
            match($0, /\+[0-9]+/)
            n = substr($0, RSTART + 1, RLENGTH - 1) + 0
            next
        }
        /^\+/ { print n; n++ }
    '
}

ERRORS=0
WARNINGS=0
FINDINGS="$TMP_DIR/findings"
: > "$FINDINGS"

for FILE in "${STAGED_FILES[@]}"; do
    KIND="$(classify "$FILE")"
    [[ "$KIND" == "generated" ]] && continue

    added_lines "$FILE" > "$TMP_DIR/lines"
    [[ -s "$TMP_DIR/lines" ]] || continue

    git show ":$FILE" > "$TMP_DIR/source" 2>/dev/null || continue

    # Seeders are one-shot data setup with no test surface an injected clock
    # would improve — the Roslyn detector downgrades them, so we skip them.
    SEEDER=0
    case "$(echo "${FILE##*/}" | tr '[:upper:]' '[:lower:]')" in
        *seed*) SEEDER=1 ;;
    esac

    while IFS='|' read -r RULE SEVERITY LINE MESSAGE SUGGESTION SNIPPET; do
        [[ -n "$RULE" ]] || continue

        if [[ "$SEVERITY" == "error" ]]; then
            ERRORS=$((ERRORS + 1))
            MARK="error  "
        else
            WARNINGS=$((WARNINGS + 1))
            MARK="warning"
        fi

        {
            printf '%s  %s:%s  [%s] %s\n' "$MARK" "$FILE" "$LINE" "$RULE" "$MESSAGE"
            printf '           %s\n' "$SNIPPET"
            printf '           → %s\n' "$SUGGESTION"
        } >> "$FINDINGS"
    done < <(awk -v kind="$KIND" -v seeder="$SEEDER" -f "$SCANNER" \
        "$TMP_DIR/lines" "$TMP_DIR/source")
done

TOTAL=$((ERRORS + WARNINGS))

if [[ $TOTAL -eq 0 ]]; then
    echo "✓ No anti-patterns detected in staged changes."
    exit 0
fi

echo "Anti-patterns detected in staged changes:"
echo ""
cat "$FINDINGS"
echo ""
echo "$ERRORS error(s), $WARNINGS warning(s)."

if [[ "${CWM_ANTIPATTERN_WARN_ONLY:-0}" == "1" ]]; then
    echo "CWM_ANTIPATTERN_WARN_ONLY=1 — reporting only, commit allowed."
    exit 0
fi

echo "Fix the findings above, suppress a line with '// cwm:ignore <rule>',"
echo "or run 'git commit --no-verify' to skip this check."
exit 1
