using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CWM.RoslynNavigator.Analyzers;

/// <summary>
/// The kind of source a syntax tree represents. Detectors declare which kinds they apply to
/// so that test fixtures, EF migrations, and compiler-generated files are not reported as
/// production anti-patterns.
/// </summary>
[Flags]
internal enum SourceKind
{
    None = 0,
    Production = 1,
    Test = 2,
    Generated = 4,
    Migration = 8,
    All = Production | Test | Generated | Migration
}

/// <summary>
/// Classifies syntax trees as production, test, generated, or migration source.
/// Classification happens at three levels because a single project can mix kinds:
/// project (test framework references), file (path and name conventions), and
/// symbol (attributes such as <c>[Fact]</c> or <c>[GeneratedCode]</c>).
/// </summary>
internal static class SourceClassifier
{
    private static readonly string[] TestFrameworkAssemblies =
    [
        "xunit.v3.core",
        "xunit.core",
        "xunit.assert",
        "nunit.framework",
        "Microsoft.VisualStudio.TestPlatform.TestFramework",
        "MSTest.TestFramework"
    ];

    private static readonly string[] TestAttributeNames =
    [
        "Fact", "FactAttribute",
        "Theory", "TheoryAttribute",
        "Test", "TestAttribute",
        "TestMethod", "TestMethodAttribute",
        "TestCase", "TestCaseAttribute",
        "Benchmark", "BenchmarkAttribute"
    ];

    private static readonly string[] GeneratedAttributeNames =
    [
        "GeneratedCode", "GeneratedCodeAttribute",
        "CompilerGenerated", "CompilerGeneratedAttribute"
    ];

    /// <summary>
    /// Whether a project is a test project, by name convention or test framework reference.
    /// </summary>
    public static bool IsTestProject(Project project, Compilation? compilation)
    {
        if (project.Name.EndsWith("Tests", StringComparison.OrdinalIgnoreCase)
            || project.Name.EndsWith("Test", StringComparison.OrdinalIgnoreCase)
            || project.Name.Contains(".Tests.", StringComparison.OrdinalIgnoreCase)
            || project.Name.Contains(".Test.", StringComparison.OrdinalIgnoreCase))
            return true;

        if (compilation is null)
            return false;

        foreach (var reference in compilation.ReferencedAssemblyNames)
        {
            foreach (var testAssembly in TestFrameworkAssemblies)
            {
                if (reference.Name.Equals(testAssembly, StringComparison.OrdinalIgnoreCase))
                    return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Classifies a syntax tree. Precedence is Generated, then Migration, then Test,
    /// then Production — a generated file inside a test project is Generated, not Test.
    /// </summary>
    /// <param name="relativePath">
    /// The path relative to the solution root. Path conventions like <c>obj/</c> and
    /// <c>tests/</c> are only meaningful within the solution: an absolute path can contain
    /// those segments anywhere above the root and would misclassify every file below it.
    /// </param>
    public static SourceKind Classify(
        SyntaxTree tree,
        string relativePath,
        bool isTestProject,
        CancellationToken ct)
    {
        var path = relativePath;

        if (IsGeneratedPath(path) || HasAutoGeneratedHeader(tree, ct))
            return SourceKind.Generated;

        if (IsMigrationPath(path))
            return SourceKind.Migration;

        if (isTestProject || IsTestPath(path))
            return SourceKind.Test;

        return SourceKind.Production;
    }

    private static bool IsGeneratedPath(string path)
    {
        if (HasDirectorySegment(path, "obj") || HasDirectorySegment(path, "bin"))
            return true;

        var fileName = Path.GetFileName(path);

        return fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".Designer.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".AssemblyInfo.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith("GlobalUsings.g.cs", StringComparison.OrdinalIgnoreCase);
    }

    private static bool IsMigrationPath(string path)
    {
        if (HasDirectorySegment(path, "Migrations"))
            return true;

        var fileName = Path.GetFileNameWithoutExtension(path);
        return fileName.EndsWith("ModelSnapshot", StringComparison.Ordinal);
    }

    private static bool IsTestPath(string path)
    {
        if (HasDirectorySegment(path, "tests") || HasDirectorySegment(path, "test"))
            return true;

        var fileName = Path.GetFileNameWithoutExtension(path);

        // Ordinal (case-sensitive) so that production names like "Contest.cs" or
        // "Manifest.cs" are not mistaken for test files.
        return fileName.EndsWith("Tests", StringComparison.Ordinal)
            || fileName.EndsWith("Test", StringComparison.Ordinal)
            || fileName.EndsWith("Spec", StringComparison.Ordinal)
            || fileName.EndsWith("Specs", StringComparison.Ordinal)
            || fileName.EndsWith("TestFixture", StringComparison.Ordinal)
            || fileName.EndsWith("TestBase", StringComparison.Ordinal);
    }

    /// <summary>
    /// Matches a whole directory segment, so "src/Objects/Foo.cs" is not treated as "obj".
    /// </summary>
    private static bool HasDirectorySegment(string path, string segment)
    {
        var span = path.AsSpan();
        var start = 0;

        for (var i = 0; i <= span.Length; i++)
        {
            if (i != span.Length && span[i] is not ('/' or '\\'))
                continue;

            var length = i - start;
            if (length == segment.Length
                && span.Slice(start, length).Equals(segment, StringComparison.OrdinalIgnoreCase))
                return true;

            start = i + 1;
        }

        return false;
    }

    private static bool HasAutoGeneratedHeader(SyntaxTree tree, CancellationToken ct)
    {
        var root = tree.GetRoot(ct);
        var firstToken = root.GetFirstToken(includeZeroWidth: true);

        foreach (var trivia in firstToken.LeadingTrivia)
        {
            if (!trivia.IsKind(SyntaxKind.SingleLineCommentTrivia)
                && !trivia.IsKind(SyntaxKind.MultiLineCommentTrivia))
                continue;

            if (trivia.ToString().Contains("<auto-generated", StringComparison.OrdinalIgnoreCase))
                return true;
        }

        return false;
    }

    /// <summary>
    /// Whether a method declaration carries a test-framework attribute. Catches test methods
    /// in classes that do not follow the *Tests.cs naming convention.
    /// </summary>
    public static bool HasTestAttribute(MethodDeclarationSyntax method) =>
        HasAnyAttribute(method.AttributeLists, TestAttributeNames);

    /// <summary>
    /// Whether a declaration is marked as compiler- or tool-generated.
    /// </summary>
    public static bool HasGeneratedAttribute(SyntaxNode node)
    {
        var lists = node switch
        {
            MemberDeclarationSyntax member => member.AttributeLists,
            _ => default
        };

        return lists.Count > 0 && HasAnyAttribute(lists, GeneratedAttributeNames);
    }

    private static bool HasAnyAttribute(SyntaxList<AttributeListSyntax> lists, string[] names)
    {
        foreach (var list in lists)
        {
            foreach (var attribute in list.Attributes)
            {
                var name = attribute.Name switch
                {
                    QualifiedNameSyntax qualified => qualified.Right.Identifier.Text,
                    SimpleNameSyntax simple => simple.Identifier.Text,
                    _ => attribute.Name.ToString()
                };

                foreach (var candidate in names)
                {
                    if (name.Equals(candidate, StringComparison.Ordinal))
                        return true;
                }
            }
        }

        return false;
    }
}
